### PR TITLE
Set up continous integration

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
setting up continous integration for org-doing. (travis, badges, test structure)

As soon as this is merged I will make a PR to have it build on `melpa` so it can be installed as a package :)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
recipe here, https://github.com/AdrieanKhisbe/melpa/commit/5c7269c9113f38938734411fc48cc2d0d66fbacd

**Comment by omouse** [comment]
I never knew how simple TravisCI looks; looks hella easier than dealing with Jenkins/Hudson. I'll review the rest of the patch later today, THANKS this is awesome :+1:

**Comment by AdrieanKhisbe** [comment]
:)
Once you have a recipe that works, that's easy peasy. héhé 
(a bit more difficult when building the recipe. ^^
that's why I'm building up https://github.com/AdrieanKhisbe/cask-package-toolset.el )

except added stub tests (unit and integration), and adding the travis, I didn't touch so far to the code.

**Comment by omouse** [comment]
merged it in and the only thing I have to do now is test it and actually write some cucumber tests, thanks again! :trophy:

**Comment by AdrieanKhisbe** [comment]
you're welcome :)

(for cucumber, really used espuds step, you'll win loooooot of time :D)

**Comment by AdrieanKhisbe** [comment]
Oops, there was a typo in the travis build.

      [Build Status](https://travis-ci.org/AdrieanKhisbe/org-doing)

I let you replace it with 

      [Build Status](https://travis-ci.org/omouse/org-doing)

Then connect to travis to activate it :)

**Comment by AdrieanKhisbe** [comment]
I also just made the PR to have org-doing on melpa:  https://github.com/milkypostman/melpa/pull/2843

Melpa badge will be working once merged and deploy :)

**Comment by AdrieanKhisbe** [comment]
was merged, soon on melpa! :)

**Pull request merged**
